name: Build Android APK
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install flet
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Build APK
        run: |
          # Adding --project to ensure it finds the name
          flet build apk --project cloner_app

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-cloner-app
          path: build/apk/*.apk
